### ISSUE TITLE
[Not Bug More Improvement]:  Method Update-PsObject.ps1 

### ISSUE THREAD

**Issue by digitalarche** [silverhack/monkey365#17]
Indeed this module as a file is found in two places in the Modules directory. One in the directory MonkeyhtmlPrivate\Utils and the other in the directory MonkeyutilsPublic. 

Moreover the method is used in the main loading module (Monkey365.psm1) but this one only loads the "*.ps1" files in all the directories listed in the declared Module array.  At no time the call to the Modules in the Core\Modules directory is made so this method is not executed. 

I know you call this method on PSM for HTML module and you declare it on PSD file for Monkeyutils and it's not the same visibility access (Private for one and Public for other) it's even to avoid maintain two versions my 2 cents. :) 

Thank you. Franck.

**Comment by silverhack** [comment]
Hey! Thanks for letting me know about this. This is because monkeyhtml and monkeyutils are written as **independent PowerShell modules** so the "Update-PsObject" function is part of each module. 

On the other hand, I can confirm that the Update-PsObject is loaded at runtime, but right now it's not necessary to load that function at .psm1, due to internal code and modules were refactored. 

This is now updated in Dev branch. 

Cheers,
